// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBErgvJN8bn1GZNNXTGdNrV5l8CwLbGmOM',
    appId: '1:362996327689:web:6d83d136a036e681fedfd8',
    messagingSenderId: '362996327689',
    projectId: 'athlepourtous',
    authDomain: 'athlepourtous.firebaseapp.com',
    storageBucket: 'athlepourtous.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYlS1o_lO8RCliMUouhx8Rg9e8E9-UT_c',
    appId: '1:362996327689:android:5106b502ffeb353efedfd8',
    messagingSenderId: '362996327689',
    projectId: 'athlepourtous',
    storageBucket: 'athlepourtous.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEprCBre2D-haA-ukIE0KBQOrQIDpS-vw',
    appId: '1:362996327689:ios:aea14318967ed72bfedfd8',
    messagingSenderId: '362996327689',
    projectId: 'athlepourtous',
    storageBucket: 'athlepourtous.appspot.com',
    iosClientId: '362996327689-iai4f2lt90pubjiat7bsfj5kupckvksp.apps.googleusercontent.com',
    iosBundleId: 'com.example.athlePourTous',
  );
}
